#!/usr/bin/zsh
# Set up the files in this repo to be used for ZSH configuration
#
#   Assumptions: (getting rid of these, safely, is how development of this file
#   should proceed).
#
#       * This repo has been cloned as ~/.zsh
#
#       * The current zsh config can be wiped out

###############################################################################
# Set up / config
###############################################################################
# ZSH built-in config files
zshfiles=(
    zshenv
    zshrc
    zlogin
)

# Read current directory, into which to create links
sourcedir=$(dirname $0:A)
###############################################################################

print "Installing ZSH config files.."
# read any zdotdir set by /etc/zshenv (sourcing that file cannot be elided.)
zdotdir=${ZDOTDIR-~}

cd $zdotdir

# Create user's ZSH config files as links to the appropriate files in the repo
print "Creating links $zdotdir -> $sourcedir.."
for zshfile in $zshfiles; do
    print "\t$zshfile.."

    if [[ -f $sourcedir/$zshfile && ! -f $zdotdir/.$zshfile ]]; then
        ln -s $sourcedir/$zshfile $zdotdir/.$zshfile
    fi
done

source ~/.zshrc
print "Done"
